"use client";
import {FormEvent,useCallback,useEffect,useState} from "react";
import type {Session} from "@supabase/supabase-js";
import {supabase} from "@/lib/supabase-browser";
import "./visual.css";

type Product={id:number;name:string;sku:string;stock:number};
type Alternative={label:string;imageUrl:string;file?:File};
type Line={productId:number;productName?:string;sku?:string;quantity:number;presentation:string;notes:string;alternatives:Alternative[]};
type AlternativeRow={id:number;label:string;image_url:string;is_selected:boolean};
type Item={id:number;quantity:number;reserved_quantity:number;presentation:string;notes:string;products:{name:string}|null;order_item_alternatives:AlternativeRow[]};
type Order={id:number;customer:string;status:string;created_at:string;order_items:Item[]};
type CatalogImage={id:number;name:string;category:string;color:string;presentation:string;image_url:string};
const blankLine=():Line=>({productId:0,quantity:1,presentation:"",notes:"",alternatives:[]});

export default function Home(){
 const [session,setSession]=useState<Session|null>(null),[email,setEmail]=useState(""),[password,setPassword]=useState("");
 const [products,setProducts]=useState<Product[]>([]),[orders,setOrders]=useState<Order[]>([]),[catalog,setCatalog]=useState<CatalogImage[]>([]),[lines,setLines]=useState<Line[]>([blankLine()]);
 const [tab,setTab]=useState<"Pedidos"|"Compras"|"Catálogo">("Pedidos"),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const [galleryLine,setGalleryLine]=useState<number|null>(null),[search,setSearch]=useState(""),[page,setPage]=useState(1),[lightbox,setLightbox]=useState<string|null>(null);
 const flash=(x:string)=>{setMessage(x);setTimeout(()=>setMessage(""),4000)};
 const load=useCallback(async()=>{if(!session)return;const [p,o,c]=await Promise.all([supabase.from("products").select("id,name,sku,stock").order("name"),supabase.from("orders").select("id,customer,status,created_at,order_items(id,quantity,reserved_quantity,presentation,notes,products(name),order_item_alternatives(id,label,image_url,is_selected))").order("created_at",{ascending:false}),supabase.from("visual_catalog").select("id,name,category,color,presentation,image_url").eq("active",true).order("created_at",{ascending:false})]);if(p.error||o.error||c.error)flash((p.error??o.error??c.error)!.message);else{setProducts((p.data??[]) as Product[]);setOrders((o.data??[]) as unknown as Order[]);setCatalog((c.data??[]) as CatalogImage[])}},[session]);
 useEffect(()=>{void supabase.auth.getSession().then(x=>setSession(x.data.session));const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{void load()},[load]);
 async function auth(mode:"in"|"up"){setBusy(true);const r=mode==="in"?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password});setBusy(false);flash(r.error?.message??(mode==="in"?"Sesión iniciada":"Cuenta creada"))}
 const updateLine=(i:number,patch:Partial<Line>)=>setLines(a=>a.map((x,n)=>n===i?{...x,...patch}:x));
 async function upload(file:File){const ext=file.name.split(".").pop()||"jpg",path=`${session!.user.id}/${crypto.randomUUID()}.${ext}`;const r=await supabase.storage.from("order-alternatives").upload(path,file);if(r.error)throw r.error;return supabase.storage.from("order-alternatives").getPublicUrl(path).data.publicUrl}
 async function addCatalogImage(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);try{const form=e.currentTarget,fd=new FormData(form),file=fd.get("image") as File;if(!file?.size)throw new Error("Selecciona una imagen");const image_url=await upload(file);const {error}=await supabase.from("visual_catalog").insert({name:String(fd.get("name")),category:String(fd.get("category")||"Cortinas"),color:String(fd.get("color")||""),presentation:String(fd.get("presentation")||""),image_url});if(error)throw error;form.reset();await load();flash("Imagen agregada al catálogo")}catch(err){flash(err instanceof Error?err.message:"No se pudo guardar")}finally{setBusy(false)}}
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const customerInput=e.currentTarget.elements.namedItem("customer") as HTMLInputElement|null;const customerName=customerInput?.value.trim()??"";if(!customerName)return flash("Captura el nombre del cliente");if(lines.some(x=>!x.productId&&!x.productName?.trim()))return flash("Captura el nombre de cada producto");setBusy(true);try{const hydrated=await Promise.all(lines.map(async x=>({...x,alternatives:await Promise.all(x.alternatives.map(async a=>({label:a.label,image_url:a.file?await upload(a.file):a.imageUrl})))})));const {error}=await supabase.rpc("create_order_with_options",{p_customer:customerName,p_items:hydrated.map(x=>({product_id:x.productId||null,product_name:x.productName?.trim()||null,sku:x.sku?.trim()||null,quantity:x.quantity,presentation:x.presentation,notes:x.notes,alternatives:x.alternatives}))});if(error)throw error;setOpen(false);setLines([blankLine()]);await load();flash("Pedido guardado")}catch(err){flash(err instanceof Error?err.message:"No se pudo guardar")}finally{setBusy(false)}}
 async function choose(itemId:number,alternativeId:number){const {error}=await supabase.rpc("select_order_alternative",{p_item_id:itemId,p_alternative_id:alternativeId});if(error)flash(error.message);else{await load();flash("Opción seleccionada")}}
 const toggle=(li:number,pic:CatalogImage)=>{const line=lines[li],exists=line.alternatives.some(a=>a.imageUrl===pic.image_url);updateLine(li,{alternatives:exists?line.alternatives.filter(a=>a.imageUrl!==pic.image_url):[...line.alternatives,{label:pic.name,imageUrl:pic.image_url}]})};
 const filtered=catalog.filter(x=>`${x.name} ${x.category} ${x.color} ${x.presentation}`.toLowerCase().includes(search.toLowerCase())),pages=Math.max(1,Math.ceil(filtered.length/18)),shown=filtered.slice((page-1)*18,page*18);
 const pending=orders.filter(o=>!["Entregado","Cancelado"].includes(o.status)).flatMap(o=>o.order_items.filter(i=>i.reserved_quantity<i.quantity).map(i=>({...i,customer:o.customer,missing:i.quantity-i.reserved_quantity})));
 if(!session)return <main className="auth"><section className="card login"><div className="logo">AO</div><h1>Almacenes Orozco</h1><p>Preview: catálogo visual</p><input type="email" placeholder="Correo" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" placeholder="Contraseña" value={password} onChange={e=>setPassword(e.target.value)}/><button disabled={busy} onClick={()=>void auth("in")}>Iniciar sesión</button><button className="secondary" disabled={busy} onClick={()=>void auth("up")}>Crear cuenta</button></section>{message&&<div className="toast">{message}</div>}</main>;
 return <div className="shell"><aside><div className="brand"><b>AO</b><span><strong>Almacenes Orozco</strong><small>Preview catálogo visual</small></span></div><nav><button className={tab==="Pedidos"?"active":""} onClick={()=>setTab("Pedidos")}>Pedidos</button><button className={tab==="Compras"?"active":""} onClick={()=>setTab("Compras")}>Compras <i>{pending.length}</i></button><button className={tab==="Catálogo"?"active":""} onClick={()=>setTab("Catálogo")}>Catálogo visual</button></nav><button className="logout" onClick={()=>void supabase.auth.signOut()}>Cerrar sesión</button></aside><main className="main"><header><div><small>PRUEBAS SEGURAS</small><h1>{tab}</h1></div>{tab!=="Catálogo"&&<button onClick={()=>setOpen(true)}>＋ Nuevo pedido</button>}</header>
 {tab==="Pedidos"&&<section className="cards">{orders.map(o=><article className="card order" key={o.id}><div className="orderHead"><div><b>PED-{1000+o.id}</b><h2>{o.customer}</h2></div><span className="status">{o.status}</span></div>{o.order_items.map(i=><div className="item" key={i.id}><div><strong>{i.quantity}× {i.products?.name}</strong><small>{[i.presentation,i.notes].filter(Boolean).join(" · ")||"Sin indicaciones"}</small><em>{i.reserved_quantity<i.quantity?`Faltan ${i.quantity-i.reserved_quantity}`:"Apartado completo"}</em></div><div className="thumbs">{i.order_item_alternatives.map(a=><button className={a.is_selected?"picked":""} key={a.id} onClick={()=>void choose(i.id,a.id)}><img src={a.image_url} alt={a.label}/><span>{a.is_selected?"✓ Elegida":a.label}</span></button>)}</div></div>)}</article>)}{!orders.length&&<div className="empty">Todavía no hay pedidos.</div>}</section>}
 {tab==="Compras"&&<section className="cards">{pending.map(i=><article className="card buy" key={i.id}><div><span className="badge">FALTAN {i.missing}</span><h2>{i.products?.name}</h2><p>{i.customer} · {i.presentation||"Sin medida"}</p><small>{i.notes}</small></div><div className="thumbs large">{i.order_item_alternatives.map(a=><button className={a.is_selected?"picked":""} key={a.id} onClick={()=>void choose(i.id,a.id)}><img src={a.image_url} alt={a.label}/><span>{a.is_selected?"✓ Comprada":a.label}</span></button>)}</div></article>)}{!pending.length&&<div className="empty">No hay artículos por surtir.</div>}</section>}
 {tab==="Catálogo"&&<section><form className="card catalogForm" onSubmit={addCatalogImage}><input name="name" required placeholder="Nombre o modelo"/><input name="category" defaultValue="Cortinas" placeholder="Categoría"/><input name="color" placeholder="Color"/><input name="presentation" placeholder="Medida"/><input name="image" required type="file" accept="image/*"/><button disabled={busy}>＋ Agregar imagen</button></form><div className="catalogGrid">{catalog.map(pic=><button className="catalogCard" key={pic.id} onClick={()=>setLightbox(pic.image_url)}><img src={pic.image_url} alt={pic.name}/><strong>{pic.name}</strong><small>{[pic.color,pic.presentation].filter(Boolean).join(" · ")||pic.category}</small></button>)}</div>{!catalog.length&&<div className="empty">Agrega las primeras imágenes del catálogo.</div>}</section>}
 </main>{open&&<div className="backdrop"><form className="modal" onSubmit={save}><button type="button" className="x" onClick={()=>setOpen(false)}>×</button><small>NUEVO PEDIDO</small><h2>Lista solicitada</h2><label>Cliente<input name="customer" required placeholder="Nombre del cliente"/></label>{lines.map((line,li)=><fieldset key={li}><div className="row"><label>Producto<select value={line.productId} onChange={e=>updateLine(li,{productId:Number(e.target.value),productName:""})}><option value="0">＋ Producto no registrado</option>{products.map(p=><option key={p.id} value={p.id}>{p.name} ({p.stock})</option>)}</select></label><label>Cantidad<input type="number" min="1" value={line.quantity} onChange={e=>updateLine(li,{quantity:Number(e.target.value)})}/></label></div>{!line.productId&&<div className="row"><label>Nombre<input required value={line.productName||""} onChange={e=>updateLine(li,{productName:e.target.value})}/></label><label>SKU opcional<input value={line.sku||""} onChange={e=>updateLine(li,{sku:e.target.value})}/></label></div>}<div className="row"><label>Presentación / medida<input placeholder="Ej. Matrimonial" value={line.presentation} onChange={e=>updateLine(li,{presentation:e.target.value})}/></label><label>Observaciones<input placeholder="Cualquiera de estas dos..." value={line.notes} onChange={e=>updateLine(li,{notes:e.target.value})}/></label></div><div className="selectedPics">{line.alternatives.map(a=><button type="button" key={a.imageUrl} onClick={()=>setLightbox(a.imageUrl)}><img src={a.imageUrl} alt={a.label}/><span>{a.label}</span></button>)}</div><button type="button" className="galleryButton" onClick={()=>{setGalleryLine(li);setPage(1);setSearch("")}}>▦ Elegir del catálogo ({line.alternatives.length})</button>{lines.length>1&&<button type="button" className="danger" onClick={()=>setLines(a=>a.filter((_,n)=>n!==li))}>Quitar artículo</button>}</fieldset>)}<button type="button" className="secondary wide" onClick={()=>setLines(a=>[...a,blankLine()])}>＋ Agregar otro artículo</button><button className="wide" disabled={busy}>{busy?"Guardando...":"Guardar pedido"}</button></form></div>}
 {galleryLine!==null&&<div className="backdrop galleryBackdrop"><section className="galleryModal"><button className="x" onClick={()=>setGalleryLine(null)}>×</button><small>CATÁLOGO VISUAL</small><h2>Identifica y elige las opciones</h2><input className="search" placeholder="Buscar por modelo, color o medida..." value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/><div className="galleryGrid">{shown.map(pic=>{const selected=lines[galleryLine].alternatives.some(a=>a.imageUrl===pic.image_url);return <article className={selected?"galleryPic selected":"galleryPic"} key={pic.id}><button className="zoom" onClick={()=>setLightbox(pic.image_url)}><img src={pic.image_url} alt={pic.name}/></button><strong>{pic.name}</strong><small>{[pic.color,pic.presentation].filter(Boolean).join(" · ")}</small><button className="selectPic" onClick={()=>toggle(galleryLine,pic)}>{selected?"✓ Seleccionada":"Seleccionar"}</button></article>})}</div><div className="pager"><button disabled={page===1} onClick={()=>setPage(x=>x-1)}>← Anterior</button><span>{page} de {pages} · {filtered.length} imágenes</span><button disabled={page===pages} onClick={()=>setPage(x=>x+1)}>Siguiente →</button></div><button className="done" onClick={()=>setGalleryLine(null)}>Listo, usar seleccionadas</button></section></div>}
 {lightbox&&<div className="lightbox" onClick={()=>setLightbox(null)}><button>×</button><img src={lightbox} alt="Vista ampliada"/></div>}{message&&<div className="toast">{message}</div>}</div>
}
