"use client";
import { FormEvent,useCallback,useEffect,useState } from "react";
import type { Session } from "@supabase/supabase-js";
import { supabase } from "@/lib/supabase-browser";

type Product={id:number;name:string;sku:string;stock:number};
type Alternative={id?:number;label:string;imageUrl:string;selected?:boolean;file?:File};
type Line={productId:number;productName?:string;sku?:string;quantity:number;presentation:string;notes:string;alternatives:Alternative[]};
type Item={id:number;product_id:number;quantity:number;reserved_quantity:number;presentation:string;notes:string;products:{name:string;sku:string}|null;order_item_alternatives:AlternativeRow[]};
type AlternativeRow={id:number;label:string;image_url:string;is_selected:boolean};
type Order={id:number;customer:string;status:string;created_at:string;order_items:Item[]};
const blankLine=():Line=>({productId:0,quantity:1,presentation:"",notes:"",alternatives:[{label:"Opción 1",imageUrl:""}]});

export default function Home(){
 const [session,setSession]=useState<Session|null>(null),[email,setEmail]=useState(""),[password,setPassword]=useState("");
 const [products,setProducts]=useState<Product[]>([]),[orders,setOrders]=useState<Order[]>([]),[lines,setLines]=useState<Line[]>([blankLine()]);
 const [tab,setTab]=useState<"Pedidos"|"Compras">("Pedidos"),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const flash=(x:string)=>{setMessage(x);setTimeout(()=>setMessage(""),4000)};
 const load=useCallback(async()=>{if(!session)return;const [p,o]=await Promise.all([supabase.from("products").select("id,name,sku,stock").order("name"),supabase.from("orders").select("id,customer,status,created_at,order_items(id,product_id,quantity,reserved_quantity,presentation,notes,products(name,sku),order_item_alternatives(id,label,image_url,is_selected))").order("created_at",{ascending:false})]);if(p.error||o.error)flash((p.error??o.error)!.message);else{setProducts((p.data??[]) as Product[]);setOrders((o.data??[]) as unknown as Order[]) }},[session]);
 useEffect(()=>{void supabase.auth.getSession().then(x=>setSession(x.data.session));const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{void load()},[load]);
 async function auth(mode:"in"|"up"){setBusy(true);const r=mode==="in"?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password});setBusy(false);flash(r.error?.message??(mode==="in"?"Sesión iniciada":"Cuenta creada"))}
 const updateLine=(i:number,patch:Partial<Line>)=>setLines(a=>a.map((x,n)=>n===i?{...x,...patch}:x));
 const updateAlt=(li:number,ai:number,patch:Partial<Alternative>)=>setLines(a=>a.map((x,n)=>n===li?{...x,alternatives:x.alternatives.map((v,m)=>m===ai?{...v,...patch}:v)}:x));
 async function upload(file:File){const ext=file.name.split(".").pop()||"jpg",path=`${session!.user.id}/${crypto.randomUUID()}.${ext}`;const r=await supabase.storage.from("order-alternatives").upload(path,file,{upsert:false});if(r.error)throw r.error;return supabase.storage.from("order-alternatives").getPublicUrl(path).data.publicUrl}
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(lines.some(x=>!x.productId&&!x.productName?.trim()))return flash("Captura el nombre de cada producto nuevo");setBusy(true);try{const hydrated=await Promise.all(lines.map(async x=>({...x,alternatives:await Promise.all(x.alternatives.filter(a=>a.file||a.imageUrl).map(async a=>({label:a.label||"Opción",image_url:a.file?await upload(a.file):a.imageUrl})))})));const customer=String(new FormData(e.currentTarget).get("customer"));const {error}=await supabase.rpc("create_order_with_options",{p_customer:customer,p_items:hydrated.map(x=>({product_id:x.productId||null,product_name:x.productName?.trim()||null,sku:x.sku?.trim()||null,quantity:x.quantity,presentation:x.presentation,notes:x.notes,alternatives:x.alternatives}))});if(error)throw error;setOpen(false);setLines([blankLine()]);await load();flash("Pedido guardado y faltantes enviados a Compras")}catch(err){flash(err instanceof Error?err.message:"No se pudo guardar")}finally{setBusy(false)}}
 async function choose(itemId:number,alternativeId:number){const {error}=await supabase.rpc("select_order_alternative",{p_item_id:itemId,p_alternative_id:alternativeId});if(error)flash(error.message);else{await load();flash("Opción comprada seleccionada")}}
 const pending=orders.filter(o=>!["Entregado","Cancelado"].includes(o.status)).flatMap(o=>o.order_items.filter(i=>i.reserved_quantity<i.quantity).map(i=>({...i,customer:o.customer,missing:i.quantity-i.reserved_quantity})));
 if(!session)return <main className="auth"><section className="card login"><div className="logo">AO</div><h1>Almacenes Orozco</h1><p>Preview: pedidos con fotos y alternativas</p><input type="email" placeholder="Correo" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" placeholder="Contraseña" value={password} onChange={e=>setPassword(e.target.value)}/><button disabled={busy} onClick={()=>void auth("in")}>Iniciar sesión</button><button className="secondary" disabled={busy} onClick={()=>void auth("up")}>Crear cuenta</button></section>{message&&<div className="toast">{message}</div>}</main>;
 return <div className="shell"><aside><div className="brand"><b>AO</b><span><strong>Almacenes Orozco</strong><small>Preview de alternativas</small></span></div><nav><button className={tab==="Pedidos"?"active":""} onClick={()=>setTab("Pedidos")}>Pedidos</button><button className={tab==="Compras"?"active":""} onClick={()=>setTab("Compras")}>Compras <i>{pending.length}</i></button></nav><button className="logout" onClick={()=>void supabase.auth.signOut()}>Cerrar sesión</button></aside><main className="main"><header><div><small>PRUEBAS SEGURAS</small><h1>{tab}</h1></div><button onClick={()=>setOpen(true)}>＋ Nuevo pedido</button></header>
 {tab==="Pedidos"?<section className="cards">{orders.map(o=><article className="card order" key={o.id}><div className="orderHead"><div><b>PED-{1000+o.id}</b><h2>{o.customer}</h2></div><span className={`status ${o.status.toLowerCase()}`}>{o.status}</span></div>{o.order_items.map(i=><div className="item" key={i.id}><div><strong>{i.quantity}× {i.products?.name}</strong><small>{[i.presentation,i.notes].filter(Boolean).join(" · ")||"Sin indicaciones"}</small><em>{i.reserved_quantity<i.quantity?`Faltan ${i.quantity-i.reserved_quantity}`:`Apartado completo`}</em></div><div className="thumbs">{i.order_item_alternatives.map(a=><button title={a.label} className={a.is_selected?"picked":""} key={a.id} onClick={()=>void choose(i.id,a.id)}><img src={a.image_url} alt={a.label}/><span>{a.is_selected?"✓ Elegida":a.label}</span></button>)}</div></div>)}</article>)}{!orders.length&&<div className="empty">Todavía no hay pedidos.</div>}</section>:
 <section className="cards">{pending.map(i=><article className="card buy" key={i.id}><div><span className="badge">FALTAN {i.missing}</span><h2>{i.products?.name}</h2><p>{i.customer} · {i.presentation||"Sin medida"}</p><small>{i.notes}</small></div><div className="thumbs large">{i.order_item_alternatives.map(a=><button className={a.is_selected?"picked":""} key={a.id} onClick={()=>void choose(i.id,a.id)}><img src={a.image_url} alt={a.label}/><span>{a.is_selected?"✓ Comprada":a.label}</span></button>)}</div></article>)}{!pending.length&&<div className="empty">No hay artículos por surtir.</div>}</section>}
 </main>{open&&<div className="backdrop"><form className="modal" onSubmit={save}><button type="button" className="x" onClick={()=>setOpen(false)}>×</button><small>NUEVO PEDIDO</small><h2>Lista solicitada</h2><label>Cliente<input name="customer" required placeholder="Nombre del cliente"/></label>{lines.map((line,li)=><fieldset key={li}><div className="row"><label>Producto<select value={line.productId} onChange={e=>updateLine(li,{productId:Number(e.target.value),productName:""})}><option value="0">＋ Producto no registrado</option>{products.map(p=><option key={p.id} value={p.id}>{p.name} ({p.stock})</option>)}</select></label><label>Cantidad<input type="number" min="1" value={line.quantity} onChange={e=>updateLine(li,{quantity:Number(e.target.value)})}/></label></div>{!line.productId&&<div className="row"><label>Nombre<input required value={line.productName||""} onChange={e=>updateLine(li,{productName:e.target.value})}/></label><label>SKU opcional<input value={line.sku||""} onChange={e=>updateLine(li,{sku:e.target.value})}/></label></div>}<div className="row"><label>Presentación / medida<input placeholder="Ej. Matrimonial" value={line.presentation} onChange={e=>updateLine(li,{presentation:e.target.value})}/></label><label>Observaciones<input placeholder="Color, precio máximo..." value={line.notes} onChange={e=>updateLine(li,{notes:e.target.value})}/></label></div><div className="alternatives"><b>Fotos u opciones aceptables</b>{line.alternatives.map((a,ai)=><div className="alt" key={ai}><input aria-label="Nombre de opción" value={a.label} onChange={e=>updateAlt(li,ai,{label:e.target.value})}/><input aria-label="Foto" type="file" accept="image/*" onChange={e=>updateAlt(li,ai,{file:e.target.files?.[0]})}/>{line.alternatives.length>1&&<button type="button" onClick={()=>updateLine(li,{alternatives:line.alternatives.filter((_,n)=>n!==ai)})}>×</button>}</div>)}<button type="button" className="link" onClick={()=>updateLine(li,{alternatives:[...line.alternatives,{label:`Opción ${line.alternatives.length+1}`,imageUrl:""}]})}>＋ Agregar otra opción</button></div>{lines.length>1&&<button type="button" className="danger" onClick={()=>setLines(a=>a.filter((_,n)=>n!==li))}>Quitar artículo</button>}</fieldset>)}<button type="button" className="secondary wide" onClick={()=>setLines(a=>[...a,blankLine()])}>＋ Agregar otro artículo</button><button className="wide" disabled={busy}>{busy?"Guardando fotos...":"Guardar pedido"}</button></form></div>}{message&&<div className="toast">{message}</div>}</div>
}
